# Generated by Django 4.2.3 on 2023-07-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectidea', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_type', models.IntegerField(choices=[(0, 'Mini project'), (1, 'Main Project'), (2, 'Live Project')])),
                ('Discription', models.TextField()),
                ('Project_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Technology', models.ManyToManyField(blank=True, null=True, to='projectidea.technology')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectidea.course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
